name: Deploy to Linux Server

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y
        
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # mkdir -p ~/.ssh
          # echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i C:\Users\bprakash27\.ssh\my linux secrets.SSH_USERNAME@secrets.SSH_HOST

